services:
  api:
    image: 954976319574.dkr.ecr.us-east-1.amazonaws.com/teamops-api:latest
    ports:
      - "80:8080"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080

      # Use Spring standard names (most reliable)
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}

      JWT_SECRET: ${JWT_SECRET}

      # If you use Redis in prod:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
